apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName.redis }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.appName.redis }}
        role: master
spec:
    ports:
        - port: 6379
          targetPort: 6379
    selector:
        app: {{ .Values.appName.redis }}
        role: master